list(
    APPEND
    PROJECT_LIBRARY
    newmat
    fslio
    newimage
    meshclass
    utils
    miscmaths
)
list(
    APPEND
    PROJECT_INCLUDE
    ${PROJECT_SOURCE_DIR}/newmat
    ${PROJECT_SOURCE_DIR}/fslio 
    ${PROJECT_SOURCE_DIR}/newimage
)